Feature/code organization
mtsmachado8/bubbles pull request #37
Opened 2020-12-04 21:23 UTC by MatheusDomingues

2020-12-04 22:08 UTC, mtsmachado8 requested changes

2020-12-04 22:08 UTC, mtsmachado8 commented on src/services/alteredLabels.ts
> +toast.configure()
_app
```suggestion
```

2020-12-04 22:08 UTC, mtsmachado8 commented on src/services/postBubbles.ts
> +toast.configure()
_app
```suggestion
```

2020-12-04 22:08 UTC, mtsmachado8 commented on src/services/postComments.ts
> +toast.configure()
_app
```suggestion
```

2020-12-04 22:08 UTC, mtsmachado8 commented on src/services/postLabels.ts
> +toast.configure()
_app
```suggestion
```

2020-12-04 22:08 UTC, mtsmachado8 commented on src/services/postLabels.ts
> +  e.preventDefault();
it would be better if we e.preventDefault() on onSubmit={e => {e.preventDefault(); callback()} so we dont have to pass it around

2020-12-04 22:08 UTC, mtsmachado8 commented on src/services/postComments.ts
> +  e.preventDefault();
it would be better if we e.preventDefault() on onSubmit={e => {e.preventDefault(); callback()} so we dont have to pass it around

2020-12-04 22:08 UTC, mtsmachado8 commented on src/services/postBubbles.ts
> +  e.preventDefault();
it would be better if we e.preventDefault() on onSubmit={e => {e.preventDefault(); callback()} so we dont have to pass it around

2020-12-04 22:08 UTC, mtsmachado8 commented on src/services/alteredLabels.ts
> +  e.preventDefault();
it would be better if we e.preventDefault() on onSubmit={e => {e.preventDefault(); callback()} so we dont have to pass it around

2020-12-04 22:08 UTC, mtsmachado8 commented on src/pages/index.tsx
> +    alteredLabels(e, id , selectedLabel, oppenedBubbleId);
it would be better if we e.preventDefault() on onSubmit={e => {e.preventDefault(); callback()} so we dont have to pass it around

2020-12-05 16:26 UTC, MatheusDomingues commented on src/components/ConfigLabel/ConfigLabel.tsx
> +          <div onClick={(e) => props.onConfigChange(e, label.id, label.selected)} className={styles.label} key={label.id}>
This event is used to prevent default event when function is called

2020-12-05 16:28 UTC, MatheusDomingues commented on src/components/ConfigLabel/ConfigLabel.tsx
> +            <div className={label.selected ? styles.addOrRemove : styles.addOrRemoveNull}>
Yes! It will get more specific. I will correct de styles name. XD

2020-12-05 16:37 UTC, MatheusDomingues commented on src/pages/bubbles/[id].tsx
> +    alteredLabels(e, id , selectedLabel, bubble.id);
Because the default event is Reload the page, but we don't want reload it. (Just for now, because SWR has not yet been implemented)

2020-12-07 18:31 UTC, mtsmachado8 approved these changes

2020-12-08 22:01 UTC, merged